### ISSUE TITLE
Pitfalls while reviewing the SwiftID reference app

### ISSUE THREAD

**Issue by bescott1** [capitalone/SwiftID-API-reference-app#13]
Hello, 

Our team at Ippon Technologies wanted to review your API and took this reference app for a test drive. We found a few pitfalls:
 
The variables oauthHost and swiftidHost are defined with URLs with an ending '/'
oauthHost is then concatenated with a string that starts with a '/' which results with an URL with two '//':
`https://api-sandbox.capitalone.com//oauth/auz/authorize`

when defining those two URL make sure they don't end in a '/'.

There were also a couple documentation issues when following the README.md:

The documentation states to run curl to register the webhook. However the Capital One server needs to connect to the reference app directly, which was impossible for us since we were behind a NAT. We resolved this issue by creating a port forward. Documenting this pitfall will probably help others in test driving this app.

Regards,
Your friends at Ippon

**Comment by lindybrandon** [comment]
Thanks for the feedback. We've corrected the cURL commands and added a note to the README regarding being behind a NAT.
